from __future__ import annotations

from collections.abc import Mapping
from datetime import UTC, datetime
from typing import Annotated, Literal, Protocol

from pydantic import Field, field_validator

from vsm.ids import new_id
from vsm.kernel.models import Identifier, NonBlank, StrictModel

REPLY_DRAFT_KIND = "reply-draft@1"

ReplyChannel = Literal["slack", "gmail", "discord", "tailscale-web"]
ReplyBody = Annotated[str, Field(min_length=1, max_length=100_000)]
AgentName = Annotated[
    str,
    Field(
        min_length=1,
        max_length=64,
        pattern=r"^[A-Za-z0-9][A-Za-z0-9_-]*$",
    ),
]


class SupplementalWriteGateway(Protocol):
    """The existing generic LETHE ``write_supplemental`` tool boundary."""

    def write_supplemental(self, **record: object) -> Mapping[str, object]: ...


class ReplyDraftSubmission(StrictModel):
    """An explicitly authored reply draft for the LETHE card queue.

    This model contains a reply body supplied by the agent. It has no method for
    generating text, approving a draft, or sending a message. The individual
    attribution is carried by the generic supplemental envelope's ``created_by``
    and ``lineage`` fields so the existing ``reply-draft@1`` payload contract is
    unchanged.
    """

    draft_id: Identifier
    incoming_observation_id: Identifier
    channel: ReplyChannel
    recipient: NonBlank
    body: ReplyBody
    drafted_at: datetime
    agent_name: AgentName
    work_item_id: Identifier
    execution_id: Identifier
    thread_ref: NonBlank | None = None

    @field_validator("drafted_at")
    @classmethod
    def drafted_at_must_be_timezone_aware(cls, value: datetime) -> datetime:
        if value.tzinfo is None or value.utcoffset() is None:
            raise ValueError("drafted_at must be timezone-aware")
        return value

    @classmethod
    def new(
        cls,
        *,
        incoming_observation_id: str,
        channel: ReplyChannel,
        recipient: str,
        body: str,
        drafted_at: datetime,
        agent_name: str,
        work_item_id: str,
        execution_id: str,
        thread_ref: str | None = None,
    ) -> "ReplyDraftSubmission":
        """Create an envelope for an already-authored body.

        ``body`` is mandatory and is never generated by this class. The caller
        must provide the incoming observation and assigned individual name.
        """

        return cls(
            draft_id=new_id("sup"),
            incoming_observation_id=incoming_observation_id,
            channel=channel,
            recipient=recipient,
            body=body,
            drafted_at=drafted_at,
            agent_name=agent_name,
            work_item_id=work_item_id,
            execution_id=execution_id,
            thread_ref=thread_ref,
        )

    def supplemental(self) -> dict[str, object]:
        """Return the exact generic supplemental envelope for ``write_supplemental``."""

        drafted_at = self.drafted_at.astimezone(UTC).isoformat().replace(
            "+00:00", "Z"
        )
        payload: dict[str, object] = {
            "channel": self.channel,
            "recipient": self.recipient,
            "body": self.body,
            "drafted_at": drafted_at,
        }
        if self.thread_ref is not None:
            payload["thread_ref"] = self.thread_ref
        return {
            "id": self.draft_id,
            "kind": REPLY_DRAFT_KIND,
            "derived_from": {
                "observations": [self.incoming_observation_id],
                "blobs": [],
                "supplementals": [],
            },
            "payload": payload,
            "created_by": f"agent:{self.agent_name}",
            "mutability": "append_only",
            "lineage": (
                f"nanihold/work-item/{self.work_item_id}/execution/"
                f"{self.execution_id}/agent/{self.agent_name}"
            ),
        }

    def submit(self, gateway: SupplementalWriteGateway) -> Mapping[str, object]:
        """Submit this authored draft through the existing LETHE write gateway.

        The gateway receives only the draft envelope. Approval and delivery are
        deliberately outside this producer boundary: the owner creates the
        ``reply-approval@1`` record and the existing channel bridge consumes the
        approved card.
        """

        response = gateway.write_supplemental(**self.supplemental())
        if not isinstance(response, Mapping):
            raise TypeError("write_supplemental must return a mapping response")
        return response


def submit_reply_draft(
    gateway: SupplementalWriteGateway,
    submission: ReplyDraftSubmission,
) -> Mapping[str, object]:
    """Submit one explicitly authored, attributed reply draft.

    This is the producer entry point used by an agent after it has written the
    body. It never creates an approval or invokes a delivery path.
    """

    return submission.submit(gateway)
