"""自己開発ループ Wave 1 のドメイン層。"""

from vsm.selfdev.models import (
    AcceptanceCriterion,
    ActorRef,
    AuditReport,
    BudgetEstimate,
    GateReport,
    PathRule,
    ProposalManifest,
    ProposalOrigin,
    PRDescription,
    RunRuntime,
    ScopeCheck,
    is_protected_path,
    proposal_to_run_manifest,
)
from vsm.selfdev.state_machine import (
    PauseCause,
    PauseKind,
    ProposalAggregate,
    ProposalPhase,
    ProposalStateMachine,
    assert_transition_allowed,
)
from vsm.selfdev.git import CandidateCommit, CandidateCommitter
from vsm.selfdev.verification import (
    ProtectedApproval,
    REQUIRED_GATES,
    ScopeCheckResult,
    canonical_scope,
    scope_sha256,
    verify_protected_approval,
    verify_scope,
)
from vsm.selfdev.workspace import ProposalWorkspace, WorkspaceController, WorkspaceDescriptor, WorkspaceStatus

__all__ = [
    "AcceptanceCriterion",
    "ActorRef",
    "AuditReport",
    "BudgetEstimate",
    "GateReport",
    "PathRule",
    "ProposalAggregate",
    "ProposalManifest",
    "ProposalOrigin",
    "ProposalPhase",
    "ProposalStateMachine",
    "PRDescription",
    "PauseCause",
    "PauseKind",
    "RunRuntime",
    "ScopeCheck",
    "assert_transition_allowed",
    "is_protected_path",
    "proposal_to_run_manifest",
    "CandidateCommit",
    "CandidateCommitter",
    "ProtectedApproval",
    "REQUIRED_GATES",
    "ScopeCheckResult",
    "canonical_scope",
    "scope_sha256",
    "verify_protected_approval",
    "verify_scope",
    "ProposalWorkspace",
    "WorkspaceController",
    "WorkspaceDescriptor",
    "WorkspaceStatus",
]
